// Mocks generated by Mockito 5.4.6 from annotations
// in artist_finance_manager/test/providers/project_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:artist_finance_manager/models/project.dart' as _i2;
import 'package:artist_finance_manager/services/project_service.dart' as _i3;
import 'package:artist_finance_manager/services/project_sync_service.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeProject_0 extends _i1.SmartFake implements _i2.Project {
  _FakeProject_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ProjectService].
///
/// See the documentation for Mockito's code generation for more information.
class MockProjectService extends _i1.Mock implements _i3.ProjectService {
  MockProjectService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set syncService(_i4.ProjectSyncService? value) => super.noSuchMethod(
        Invocation.setter(
          #syncService,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<List<_i2.Project>> loadProjects() => (super.noSuchMethod(
        Invocation.method(
          #loadProjects,
          [],
        ),
        returnValue: _i5.Future<List<_i2.Project>>.value(<_i2.Project>[]),
      ) as _i5.Future<List<_i2.Project>>);

  @override
  _i5.Future<List<_i2.Project>> loadAllProjects() => (super.noSuchMethod(
        Invocation.method(
          #loadAllProjects,
          [],
        ),
        returnValue: _i5.Future<List<_i2.Project>>.value(<_i2.Project>[]),
      ) as _i5.Future<List<_i2.Project>>);

  @override
  _i5.Future<_i2.Project> createProject(String? name) => (super.noSuchMethod(
        Invocation.method(
          #createProject,
          [name],
        ),
        returnValue: _i5.Future<_i2.Project>.value(_FakeProject_0(
          this,
          Invocation.method(
            #createProject,
            [name],
          ),
        )),
      ) as _i5.Future<_i2.Project>);

  @override
  _i5.Future<void> updateProject(_i2.Project? project) => (super.noSuchMethod(
        Invocation.method(
          #updateProject,
          [project],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> deleteProject(String? projectId) => (super.noSuchMethod(
        Invocation.method(
          #deleteProject,
          [projectId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<String?> getCurrentProjectId() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentProjectId,
          [],
        ),
        returnValue: _i5.Future<String?>.value(),
      ) as _i5.Future<String?>);

  @override
  _i5.Future<void> setCurrentProjectId(String? projectId) =>
      (super.noSuchMethod(
        Invocation.method(
          #setCurrentProjectId,
          [projectId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i2.Project> ensureDefaultProject() => (super.noSuchMethod(
        Invocation.method(
          #ensureDefaultProject,
          [],
        ),
        returnValue: _i5.Future<_i2.Project>.value(_FakeProject_0(
          this,
          Invocation.method(
            #ensureDefaultProject,
            [],
          ),
        )),
      ) as _i5.Future<_i2.Project>);

  @override
  _i5.Future<void> clearAll() => (super.noSuchMethod(
        Invocation.method(
          #clearAll,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}
