// File generated by FlutterFire CLI.
// This file should be updated with your actual Firebase project configuration
// You can get these values from: https://console.firebase.google.com/project/artist-manager-479514/settings/general

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByeWBa2uve6USy6mTUrK8oAyfmY55tHZM',
    appId: '1:456648586026:web:941da4e3ac52b46407e453',
    messagingSenderId: '456648586026',
    projectId: 'artist-manager-479514',
    authDomain: 'artist-manager-479514.firebaseapp.com',
    storageBucket: 'artist-manager-479514.firebasestorage.app',
    measurementId: 'G-LX4EY29TF0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXf8qHJN_KGvXJZvXqP9yXYqP9yXYqP9',
    appId: '1:456648586026:android:XXXXXXXXXXXXXXXXXX',
    messagingSenderId: '456648586026',
    projectId: 'artist-manager-479514',
    authDomain: 'artist-manager-479514.firebaseapp.com',
    storageBucket: 'artist-manager-479514.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXf8qHJN_KGvXJZvXqP9yXYqP9yXYqP9',
    appId: '1:456648586026:ios:XXXXXXXXXXXXXXXXXX',
    messagingSenderId: '456648586026',
    projectId: 'artist-manager-479514',
    authDomain: 'artist-manager-479514.firebaseapp.com',
    storageBucket: 'artist-manager-479514.appspot.com',
    iosBundleId: 'com.artist.financemanager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXf8qHJN_KGvXJZvXqP9yXYqP9yXYqP9',
    appId: '1:456648586026:ios:XXXXXXXXXXXXXXXXXX',
    messagingSenderId: '456648586026',
    projectId: 'artist-manager-479514',
    authDomain: 'artist-manager-479514.firebaseapp.com',
    storageBucket: 'artist-manager-479514.appspot.com',
    iosBundleId: 'com.artist.financemanager',
  );
}
