#!/bin/bash

# Script to check Firebase email configuration
# This helps diagnose email link authentication issues

echo "🔍 Firebase Email Configuration Checker"
echo "========================================"
echo ""

PROJECT_ID="artist-manager-479514"

echo "📋 To check if emails are being sent from Firebase:"
echo ""
echo "1. Firebase Console - Check Email Templates:"
echo "   https://console.firebase.google.com/project/${PROJECT_ID}/authentication/emails"
echo ""
echo "2. Firebase Console - Check Recent Email Activity:"
echo "   Go to: Authentication > Templates > Email link sign-in"
echo "   Check if the template is enabled and configured"
echo ""
echo "3. Firebase Console - Check Authentication Logs:"
echo "   https://console.firebase.google.com/project/${PROJECT_ID}/authentication/users"
echo "   Look for recent sign-in attempts"
echo ""
echo "4. GCP Logging - Check Email Send Logs:"
echo "   https://console.cloud.google.com/logs/query?project=${PROJECT_ID}"
echo "   Use this query:"
echo '   resource.type="cloud_function"'
echo '   OR textPayload=~"email"'
echo ""
echo "5. Firebase Console - Email Provider Settings:"
echo "   https://console.firebase.google.com/project/${PROJECT_ID}/authentication/providers"
echo "   Ensure 'Email/Password' is enabled"
echo "   Check 'Email link (passwordless sign-in)' is enabled"
echo ""
echo "📊 Current Project Info:"
echo "   Project ID: ${PROJECT_ID}"
echo "   Auth Domain: ${PROJECT_ID}.firebaseapp.com"
echo ""
echo "⚠️  Common Issues:"
echo "   - Email link auth not enabled in Firebase Console"
echo "   - Custom email action handler URL not configured"
echo "   - SMTP/Email delivery quota limits reached"
echo "   - Email going to spam folder"
echo "   - Authorized domain (localhost) not configured for testing"
echo ""
echo "💡 Firebase doesn't use SMTP - it sends emails directly via GCP"
echo "   There's no SMTP queue to check. Emails are sent immediately or fail."
echo ""
echo "🔧 Quick Fixes:"
echo "   1. Check browser console for errors (F12 in Chrome)"
echo "   2. Look for console.log messages from the app"
echo "   3. Verify email in Firebase Console > Authentication > Users"
echo "   4. Check spam/junk folder"
echo ""
